server:
  tomcat:
    # uri编码
    uri-encoding: UTF-8
    # Tomcat基目录, 如果未指定则使用临时目录, core根据系统环境指定。
    basedir: ${spring.application.name}
    # 最大工作线程数，默认200
    threads.max: 200
    # 最大连接数：Tomcat同一时间能接受的最大线程数量，需要大于 max-threads + accept-count，默认8192
    max-connections: 5000
    # 最大等待队列长度：每个请求使用一个线程，线程数超过最大链接数后请求会进入等待队列，直到有线程处理
    accept-count: 100
    # 连接建立超时时间（单位：ms）
    connection-timeout: 600000
    # 请求体最大长度（单位：KB）
    max-http-form-post-size: 1024