spring:
  thymeleaf:
    # 开启模板缓存（默认值：true）
    cache: true
    # 模板编码
    encoding: UTF-8
    # 是否在呈现模板之前检查模板是否存在
    check-template: true
    # 检查模板位置是否正确（默认值:true）
    check-template-location: false
    #servlet:
    #  content-type: text/html  #Content-Type的值（默认值：text/html）
    #enabled: true #开启MVC Thymeleaf视图解析（默认值：true）
    #excluded-view-names: #要被排除在解析之外的视图名称列表，用逗号分隔
    #mode: HTML #要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    #prefix: classpath:/templates/  #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    #suffix: .html #在构建URL时添加到视图名称后的后缀（默认值：.html）
    #template-resolver-order: #Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
    #view-names: #可解析的视图名称列表，用逗号分隔